name: Development

on:
  - push
  - workflow_dispatch

jobs:
  Test:
    uses: BlockProject3D/workflows/.github/workflows/Build_Test.yml@main
    with:
      rust_components: rust-src

  Analyze:
    uses: BlockProject3D/workflows/.github/workflows/Analyze.yml@main
    needs: Test

  Coverage:
    uses: BlockProject3D/workflows/.github/workflows/Coverage.yml@main
    with:
      rust_components: rust-src

  Release:
    uses: BlockProject3D/workflows/.github/workflows/Release.yml@main
    needs: Test
    secrets:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
